name = bloque_simple
title = Bloque Simple (simple block)
description = This mod adds a simple block that has a PNG of my cat with very insane audio. I'm not making this mod with a serious purpose, but rather as a test for Luanti's database content. 
author = juha
